"""added coupons

Revision ID: 08a5880551aa
Revises: c0fbd1ecc129
Create Date: 2021-06-07 09:55:15.156963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a5880551aa'
down_revision = 'c0fbd1ecc129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons_redeemed',
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_redeemed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons_redeemed')
    op.drop_table('coupon')
    # ### end Alembic commands ###
