"""add is active to department

Revision ID: 0d17f50ccb5a
Revises: 8206737b975f
Create Date: 2021-06-22 16:56:20.631266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d17f50ccb5a'
down_revision = '8206737b975f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column(
        'is_active', sa.Boolean(), default=True, server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'is_active')
    # ### end Alembic commands ###
