"""add is_featured tags

Revision ID: 1ef9b08d23bd
Revises: 560091a6cb45
Create Date: 2021-06-16 11:43:35.777529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef9b08d23bd'
down_revision = '560091a6cb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tag', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_tag', 'is_featured')
    # ### end Alembic commands ###
