"""added address is_servicable

Revision ID: 21bb1cd4a397
Revises: 373a9b88e7b5
Create Date: 2021-05-17 08:59:34.440124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bb1cd4a397'
down_revision = '373a9b88e7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('is_serviceable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'is_serviceable')
    # ### end Alembic commands ###
