"""added date_paid

Revision ID: 2360c8e0baa9
Revises: 666f0c1e3f98
Create Date: 2021-04-26 12:47:28.919692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2360c8e0baa9'
down_revision = '666f0c1e3f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'stripe_payment_intent_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('stripe_payment_intent_secret', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
