"""typo

Revision ID: 265400bbf6b9
Revises: 5baf4d2b1cc5
Create Date: 2021-07-02 15:55:28.406918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '265400bbf6b9'
down_revision = '5baf4d2b1cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('preparation_time_seconds', sa.Integer(), nullable=True))
    op.drop_column('recipe', 'preperation_time_seconds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('preperation_time_seconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'preparation_time_seconds')
    # ### end Alembic commands ###
