"""changed to query

Revision ID: 2ae1baa2e386
Revises: 1491a980968f
Create Date: 2021-04-19 15:00:07.449512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ae1baa2e386'
down_revision = '1491a980968f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_search', sa.Column('query', sa.String(length=100), nullable=True))
    op.drop_column('popular_search', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_search', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('popular_search', 'query')
    # ### end Alembic commands ###
