"""add order

Revision ID: 2dda3fb67ef3
Revises: c3e09df6a360
Create Date: 2021-06-18 11:24:15.765116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dda3fb67ef3'
down_revision = 'c3e09df6a360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tag', sa.Column('order', sa.SmallInteger(), nullable=True))
    op.add_column('search', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'search', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search', type_='foreignkey')
    op.drop_column('search', 'user_id')
    op.drop_column('product_tag', 'order')
    # ### end Alembic commands ###
