"""added phone/referral

Revision ID: 373a9b88e7b5
Revises: 8349d9747957
Create Date: 2021-05-13 11:30:21.314358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373a9b88e7b5'
down_revision = '8349d9747957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('credit_used', sa.Integer(), nullable=True))
    op.drop_index('referral_code', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('referral_code', 'user', ['referral_code'], unique=True)
    op.drop_column('order', 'credit_used')
    # ### end Alembic commands ###
