"""added percent discount

Revision ID: 427196387768
Revises: bcd07da0525a
Create Date: 2021-04-08 15:50:11.420967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427196387768'
down_revision = 'bcd07da0525a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('percent_discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'percent_discount')
    # ### end Alembic commands ###
