"""added out_for_delivery enum, added refund requests

Revision ID: 55772a4b8407
Revises: a95038831900
Create Date: 2021-04-21 11:10:17.796015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '55772a4b8407'
down_revision = 'a95038831900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column(
        'refund_requested', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    conn.execute(
        text(
            """
    ALTER TABLE `order` MODIFY `order`.`status` ENUM(
        'failed', 
        'checking_out', 
        'paid', 
        'preparing',
        'out_for_delivery',
        'delivered',
        'arrived',
        'complete')
        """
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'refund_requested')
    # ### end Alembic commands ###
