"""add out_for_deliver enum

Revision ID: 560091a6cb45
Revises: 9ad634850c7e
Create Date: 2021-06-14 11:00:47.083087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '560091a6cb45'
down_revision = '9ad634850c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            """
    ALTER TABLE `order` MODIFY `order`.`status` ENUM(
        'failed', 
        'checking_out', 
        'paid', 
        'preparing',
        'out_for_delivery',
        'arrived',
        'delivered',
        'complete')
        """
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
