"""make recipe item/recipes

Revision ID: 5baf4d2b1cc5
Revises: a22acbddab6e
Create Date: 2021-06-30 14:34:54.610710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5baf4d2b1cc5'
down_revision = 'a22acbddab6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.Column('image_url', sa.String(
                        length=300), nullable=True),
                    sa.Column('preperation_time_seconds',
                              sa.Integer(), nullable=True),
                    sa.Column('cooking_time_seconds',
                              sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('recipe_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('recipe_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('recipe_item_type', sa.Enum('required', 'things_you_may_have', 'substitution',
                                                          name='recipeitemtypeenum'), server_default='required', nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_item')
    op.drop_table('recipe')
    # ### end Alembic commands ###
