"""Increase product description length

Revision ID: 5d11e1021612
Revises: ebd61970a727
Create Date: 2021-09-08 17:16:39.265604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d11e1021612'
down_revision = 'ebd61970a727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('recipe', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user', 'profile_picture_url',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture_url',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('recipe', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
