"""remove user

Revision ID: 634d94e6e925
Revises: 2dda3fb67ef3
Create Date: 2021-06-18 11:25:01.975400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '634d94e6e925'
down_revision = '2dda3fb67ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('search_ibfk_1', 'search', type_='foreignkey')
    op.drop_column('search', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('search_ibfk_1', 'search', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
