"""added phone_verification

Revision ID: 644bb79fa316
Revises: 2360c8e0baa9
Create Date: 2021-04-27 14:06:26.643486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644bb79fa316'
down_revision = '2360c8e0baa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone_verification_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_verification_code')
    op.drop_column('user', 'is_phone_verified')
    # ### end Alembic commands ###
