"""added date_paid

Revision ID: 666f0c1e3f98
Revises: 49699abef36b
Create Date: 2021-04-26 12:27:38.338082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666f0c1e3f98'
down_revision = '49699abef36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('stripe_payment_intent_secret', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'stripe_payment_intent_secret')
    op.drop_table('product_suggestion')
    # ### end Alembic commands ###
