"""add cateogory is active





Revision ID: 720737587a45
Revises: c5767a0f7ad3
Create Date: 2021-06-22 17:06:24.984406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720737587a45'
down_revision = 'c5767a0f7ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_active')
    # ### end Alembic commands ###
