"""increase string

Revision ID: 7f3e810443a3
Revises: c33a3ff96e7b
Create Date: 2021-05-20 09:54:56.072612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3e810443a3'
down_revision = 'c33a3ff96e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
