"""add brand name

Revision ID: 8206737b975f
Revises: 634d94e6e925
Create Date: 2021-06-18 15:43:20.771485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8206737b975f'
down_revision = '634d94e6e925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand_name', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'brand_name')
    # ### end Alembic commands ###
