"""added product_id

Revision ID: 82aa4bfcd72d
Revises: c7ab185116f2
Create Date: 2021-04-07 15:31:31.215022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82aa4bfcd72d'
down_revision = 'c7ab185116f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_ordered', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_ordered', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_ordered', type_='foreignkey')
    op.drop_column('product_ordered', 'product_id')
    # ### end Alembic commands ###
