"""added phone/referral

Revision ID: 8349d9747957
Revises: cbc0d965954e
Create Date: 2021-05-13 10:31:24.379134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8349d9747957'
down_revision = 'cbc0d965954e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
