"""added date created last updated

Revision ID: 8cd0ce3bdab2
Revises: 427196387768
Create Date: 2021-04-12 21:34:29.608200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd0ce3bdab2'
down_revision = '427196387768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('address', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'last_login')
    op.drop_column('address', 'date_created')
    # ### end Alembic commands ###
