"""add date_arrived enum

Revision ID: 9ad634850c7e
Revises: d0f70eb55a79
Create Date: 2021-06-14 10:47:03.081703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text
# revision identifiers, used by Alembic.
revision = '9ad634850c7e'
down_revision = 'd0f70eb55a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            """
    ALTER TABLE `order` MODIFY `order`.`status` ENUM(
        'checking_out',
        'paid',
        'preparing',
        'arrived',
        'delivered',
        'complete',
        'failed'
        )
        """
        ))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column(
        'date_arrived', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
