"""empty message

Revision ID: 9df0bd1fb304
Revises: c72b21e0d6fc
Create Date: 2021-07-12 16:09:41.433689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df0bd1fb304'
down_revision = 'c72b21e0d6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=True),
    sa.Column('date_adjusted', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('spoilage', 'damage', 'inventory_error', 'theft', 'delivery_error', 'writeoff', name='adjustmentreason'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_purchased',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('date_expiry', sa.DateTime(), nullable=True),
    sa.Column('location_purchased', sa.String(200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_purchased')
    op.drop_table('inventory_adjustment')
    # ### end Alembic commands ###
