"""make recipe item/recipes

Revision ID: a22acbddab6e
Revises: 54f167789120
Create Date: 2021-06-30 14:34:19.037361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22acbddab6e'
down_revision = '54f167789120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_tag', sa.Column('display_afternoon', sa.Boolean(), nullable=True))
    op.add_column('product_tag', sa.Column('display_evening', sa.Boolean(), nullable=True))
    op.add_column('product_tag', sa.Column('display_morning', sa.Boolean(), nullable=True))
    op.add_column('product_tag', sa.Column('display_night', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_tag', 'display_night')
    op.drop_column('product_tag', 'display_morning')
    op.drop_column('product_tag', 'display_evening')
    op.drop_column('product_tag', 'display_afternoon')
    # ### end Alembic commands ###
