"""added is_user_abandoned_cart_notified

Revision ID: a517546a4f22
Revises: 5c1f45c4d0f2
Create Date: 2021-06-07 16:01:40.105300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a517546a4f22'
down_revision = '5c1f45c4d0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_user_abandoned_cart_notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_user_abandoned_cart_notified')
    # ### end Alembic commands ###
