"""added promo code

Revision ID: a64a7a710fca
Revises: b35f1837dfe1
Create Date: 2021-06-13 13:40:56.718054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64a7a710fca'
down_revision = 'b35f1837dfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
