"""added address city, order dates, product tax

Revision ID: a76ec9630978
Revises: 55772a4b8407
Create Date: 2021-04-22 08:51:12.426471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76ec9630978'
down_revision = '55772a4b8407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('product', sa.Column('tax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'tax')
    op.drop_column('address', 'city')
    # ### end Alembic commands ###
