"""added lat long

Revision ID: a95038831900
Revises: 2ae1baa2e386
Create Date: 2021-04-21 11:04:46.236648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a95038831900'
down_revision = '2ae1baa2e386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('address', sa.Column('longitude', sa.Float(), nullable=False))
    op.alter_column('address', 'country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('address', 'province',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('address', 'street_address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('order', sa.Column('additional_instruction', sa.String(length=200), nullable=True))
    op.add_column('order', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'longitude')
    op.drop_column('order', 'latitude')
    op.drop_column('order', 'additional_instruction')
    op.alter_column('address', 'street_address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('address', 'province',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('address', 'country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('address', 'longitude')
    op.drop_column('address', 'latitude')
    # ### end Alembic commands ###
