"""added promo code

Revision ID: b35f1837dfe1
Revises: 78fa660bcef3
Create Date: 2021-06-13 13:30:55.890520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b35f1837dfe1'
down_revision = '78fa660bcef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('num_redeems_allowed', sa.Integer(), nullable=True))
    op.drop_constraint('promo_code_ibfk_1', 'promo_code', type_='foreignkey')
    op.drop_column('promo_code', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('promo_code_ibfk_1', 'promo_code', 'order', ['order_id'], ['id'])
    op.drop_column('promo_code', 'num_redeems_allowed')
    # ### end Alembic commands ###
