"""added stripefields

Revision ID: b9d7f056d37b
Revises: 1e33396e2700
Create Date: 2021-04-07 17:10:21.984751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d7f056d37b'
down_revision = '1e33396e2700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('stripe_payment_intent', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('stripe_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_id')
    op.drop_column('order', 'stripe_payment_intent')
    # ### end Alembic commands ###
