"""added default value

Revision ID: bcd07da0525a
Revises: b9d7f056d37b
Create Date: 2021-04-08 11:19:13.916103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd07da0525a'
down_revision = 'b9d7f056d37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('directus_presets_collection_foreign', table_name='directus_presets')
    op.drop_table('directus_presets')
    op.drop_table('directus_webhooks')
    op.drop_table('directus_folders')
    op.drop_index('directus_permissions_collection_foreign', table_name='directus_permissions')
    op.drop_table('directus_permissions')
    op.drop_table('directus_settings')
    op.drop_index('directus_activity_collection_foreign', table_name='directus_activity')
    op.drop_table('directus_activity')
    op.drop_table('directus_migrations')
    op.drop_table('directus_collections')
    op.drop_table('directus_roles')
    op.drop_table('directus_sessions')
    op.drop_index('directus_revisions_collection_foreign', table_name='directus_revisions')
    op.drop_table('directus_revisions')
    op.drop_table('directus_files')
    op.drop_index('directus_fields_collection_foreign', table_name='directus_fields')
    op.drop_table('directus_fields')
    op.drop_index('directus_users_email_unique', table_name='directus_users')
    op.drop_table('directus_users')
    op.drop_index('directus_relations_many_collection_foreign', table_name='directus_relations')
    op.drop_index('directus_relations_one_collection_foreign', table_name='directus_relations')
    op.drop_table('directus_relations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directus_relations',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('many_collection', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('many_field', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('many_primary', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('one_collection', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('one_field', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('one_primary', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('one_collection_field', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('one_allowed_collections', mysql.TEXT(), nullable=True),
    sa.Column('junction_field', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sort_field', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_relations_one_collection_foreign', 'directus_relations', ['one_collection'], unique=False)
    op.create_index('directus_relations_many_collection_foreign', 'directus_relations', ['many_collection'], unique=False)
    op.create_table('directus_users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('avatar', mysql.CHAR(length=36), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=8), server_default=sa.text("'en-US'"), nullable=True),
    sa.Column('theme', mysql.VARCHAR(length=20), server_default=sa.text("'auto'"), nullable=True),
    sa.Column('tfa_secret', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('role', mysql.CHAR(length=36), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_access', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_page', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['directus_roles.id'], name='directus_users_role_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_users_email_unique', 'directus_users', ['email'], unique=True)
    op.create_table('directus_fields',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('collection', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('field', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('special', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('interface', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('options', mysql.JSON(), nullable=True),
    sa.Column('display', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('display_options', mysql.JSON(), nullable=True),
    sa.Column('readonly', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('hidden', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('sort', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('width', mysql.VARCHAR(length=30), server_default=sa.text("'full'"), nullable=True),
    sa.Column('group', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('translations', mysql.JSON(), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['directus_fields.id'], name='directus_fields_group_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_fields_collection_foreign', 'directus_fields', ['collection'], unique=False)
    op.create_table('directus_files',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('storage', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('filename_disk', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('filename_download', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('folder', mysql.CHAR(length=36), nullable=True),
    sa.Column('uploaded_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('uploaded_on', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('modified_on', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('charset', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('filesize', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('width', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('height', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('embed', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.TEXT(), nullable=True),
    sa.Column('tags', mysql.TEXT(), nullable=True),
    sa.Column('metadata', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['folder'], ['directus_folders.id'], name='directus_files_folder_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['directus_users.id'], name='directus_files_modified_by_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['directus_users.id'], name='directus_files_uploaded_by_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_revisions',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('activity', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('collection', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('item', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('delta', mysql.JSON(), nullable=True),
    sa.Column('parent', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity'], ['directus_activity.id'], name='directus_revisions_activity_foreign', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent'], ['directus_revisions.id'], name='directus_revisions_parent_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_revisions_collection_foreign', 'directus_revisions', ['collection'], unique=False)
    op.create_table('directus_sessions',
    sa.Column('token', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user', mysql.CHAR(length=36), nullable=False),
    sa.Column('expires', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['directus_users.id'], name='directus_sessions_user_foreign', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_roles',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=30), server_default=sa.text("'supervised_user_circle'"), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('ip_access', mysql.TEXT(), nullable=True),
    sa.Column('enforce_tfa', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('module_list', mysql.JSON(), nullable=True),
    sa.Column('collection_list', mysql.JSON(), nullable=True),
    sa.Column('admin_access', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('app_access', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_collections',
    sa.Column('collection', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('display_template', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hidden', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('singleton', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('translations', mysql.JSON(), nullable=True),
    sa.Column('archive_field', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('archive_app_filter', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('archive_value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('unarchive_value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sort_field', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('collection'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_migrations',
    sa.Column('version', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('version'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_activity',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('user', mysql.CHAR(length=36), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('collection', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('item', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_activity_collection_foreign', 'directus_activity', ['collection'], unique=False)
    op.create_table('directus_settings',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=100), server_default=sa.text("'Directus'"), nullable=False),
    sa.Column('project_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('project_color', mysql.VARCHAR(length=10), server_default=sa.text("'#00C897'"), nullable=True),
    sa.Column('project_logo', mysql.CHAR(length=36), nullable=True),
    sa.Column('public_foreground', mysql.CHAR(length=36), nullable=True),
    sa.Column('public_background', mysql.CHAR(length=36), nullable=True),
    sa.Column('public_note', mysql.TEXT(), nullable=True),
    sa.Column('auth_login_attempts', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'25'"), autoincrement=False, nullable=True),
    sa.Column('auth_password_policy', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('storage_asset_transform', mysql.VARCHAR(length=7), server_default=sa.text("'all'"), nullable=True),
    sa.Column('storage_asset_presets', mysql.JSON(), nullable=True),
    sa.Column('custom_css', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['project_logo'], ['directus_files.id'], name='directus_settings_project_logo_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['public_background'], ['directus_files.id'], name='directus_settings_public_background_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['public_foreground'], ['directus_files.id'], name='directus_settings_public_foreground_foreign', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_permissions',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('role', mysql.CHAR(length=36), nullable=True),
    sa.Column('collection', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('permissions', mysql.JSON(), nullable=True),
    sa.Column('validation', mysql.JSON(), nullable=True),
    sa.Column('presets', mysql.JSON(), nullable=True),
    sa.Column('fields', mysql.TEXT(), nullable=True),
    sa.Column('limit', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role'], ['directus_roles.id'], name='directus_permissions_role_foreign', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_permissions_collection_foreign', 'directus_permissions', ['collection'], unique=False)
    op.create_table('directus_folders',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('parent', mysql.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['directus_folders.id'], name='directus_folders_parent_foreign', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_webhooks',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=10), server_default=sa.text("'POST'"), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), server_default=sa.text("'active'"), nullable=False),
    sa.Column('data', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('actions', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('collections', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('directus_presets',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('bookmark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user', mysql.CHAR(length=36), nullable=True),
    sa.Column('role', mysql.CHAR(length=36), nullable=True),
    sa.Column('collection', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('search', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('filters', mysql.JSON(), nullable=True),
    sa.Column('layout', mysql.VARCHAR(length=100), server_default=sa.text("'tabular'"), nullable=True),
    sa.Column('layout_query', mysql.JSON(), nullable=True),
    sa.Column('layout_options', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['directus_roles.id'], name='directus_presets_role_foreign', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['directus_users.id'], name='directus_presets_user_foreign', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('directus_presets_collection_foreign', 'directus_presets', ['collection'], unique=False)
    # ### end Alembic commands ###
