"""added shelf

Revision ID: c0fbd1ecc129
Revises: fba68dd9daae
Create Date: 2021-06-03 14:15:47.628634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fbd1ecc129'
down_revision = 'fba68dd9daae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('shelf_number', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'shelf_number')
    # ### end Alembic commands ###
