"""add ability to let promo code only work for first oder

Revision ID: c2a1e326854b
Revises: 10e498b95e5a
Create Date: 2021-07-23 17:16:46.412119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a1e326854b'
down_revision = '10e498b95e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('only_first_order', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_code', 'only_first_order')
    # ### end Alembic commands ###
