"""added address google_share_url/seconds_away_from_hq

Revision ID: c33a3ff96e7b
Revises: 21bb1cd4a397
Create Date: 2021-05-20 09:41:18.437156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33a3ff96e7b'
down_revision = '21bb1cd4a397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('google_share_url',
                                       sa.String(length=250), nullable=True))
    op.add_column('address', sa.Column(
        'seconds_away_from_hq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'seconds_away_from_hq')
    op.drop_column('address', 'google_share_url')
    # ### end Alembic commands ###
