"""add promo_code_credit

Revision ID: c3e09df6a360
Revises: e4d14c1982f1
Create Date: 2021-06-17 16:36:52.238359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e09df6a360'
down_revision = 'e4d14c1982f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('promo_code_credit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'promo_code_credit')
    # ### end Alembic commands ###
