"""add is active to department

Revision ID: c5767a0f7ad3
Revises: 0d17f50ccb5a
Create Date: 2021-06-22 16:59:13.403561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5767a0f7ad3'
down_revision = '0d17f50ccb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
