"""empty message

Revision ID: c72b21e0d6fc
Revises: 10e498b95e5a
Create Date: 2021-07-12 15:44:14.726685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72b21e0d6fc'
down_revision = '10e498b95e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
