"""added models

Revision ID: c7ab185116f2
Revises: 600f6cc5ce8c
Create Date: 2021-04-06 16:15:47.617022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7ab185116f2'
down_revision = '600f6cc5ce8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('picture_url', sa.String(
                        length=400), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product_tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('address',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('street_address', sa.String(
                        length=100), nullable=True),
                    sa.Column('apartment_number', sa.String(
                        length=30), nullable=True),
                    sa.Column('buzzer', sa.String(length=20), nullable=True),
                    sa.Column('postal_code', sa.String(
                        length=20), nullable=True),
                    sa.Column('province', sa.String(length=20), nullable=True),
                    sa.Column('country', sa.String(length=50), nullable=True),
                    sa.Column('is_default', sa.Boolean(), nullable=True),
                    sa.Column('additional_instructions',
                              sa.String(length=200), nullable=True),
                    sa.Column('delivery_preference', sa.Enum('leave_at_door', 'buzz_up',
                                                             'call_upon_arrival', 'meet_downstairs', name='deliverypreferenceenum')),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('department_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['department_id'], ['department.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('feedback', sa.String(
                        length=200), nullable=True),
                    sa.Column('stars', sa.Enum('one', 'two', 'three', 'four',
                                               'five', name='starratingenum'), nullable=True),
                    sa.Column('cost', sa.Float(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_delivered', sa.DateTime(), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Enum('failed', 'paid', 'preparing', 'delivered',
                                                'arrived', 'complete', name='orderstatusenum'), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=200), nullable=True),
                    sa.Column('stock', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(
                        length=300), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('department_id', sa.Integer(), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.Column('weight', sa.Integer(), nullable=True),
                    sa.Column('cost', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category.id'], ),
                    sa.ForeignKeyConstraint(
                        ['department_id'], ['department.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product_ordered',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.SmallInteger(), nullable=True),
                    sa.Column('date_ordered', sa.DateTime(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('favorite_products',
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    op.create_table('product_image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(length=200), nullable=True),
                    sa.Column('date_added', sa.DateTime(), nullable=True),
                    sa.Column('image_url', sa.String(
                        length=400), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product_tags',
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['product_tag.id'], )
                    )
    op.add_column('user', sa.Column(
        'last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column(
        'referral_id', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column(
        'referrer_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum(
        'admin', 'user', name='userroleenum'), server_default='user', nullable=False))
    op.drop_column('user', 'address')
    op.drop_column('user', 'country')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'city', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('user', sa.Column(
        'postal_code', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('user', sa.Column(
        'country', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('user', sa.Column(
        'address', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('user', 'role')
    op.drop_column('user', 'referrer_id')
    op.drop_column('user', 'referral_id')
    op.drop_column('user', 'last_login')
    op.drop_table('product_tags')
    op.drop_table('product_image')
    op.drop_table('favorite_products')
    op.drop_table('product_ordered')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('category')
    op.drop_table('address')
    op.drop_table('product_tag')
    op.drop_table('department')
    # ### end Alembic commands ###
