"""added phone/referral

Revision ID: cbc0d965954e
Revises: 904c91adc946
Create Date: 2021-05-13 10:30:32.799967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbc0d965954e'
down_revision = '904c91adc946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credit', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone_country_code', sa.String(length=5), nullable=True))
    op.add_column('user', sa.Column('referral_code', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'user', ['referral_code'])
    op.drop_column('user', 'referral_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_id', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'referral_code')
    op.drop_column('user', 'phone_country_code')
    op.drop_column('user', 'credit')
    # ### end Alembic commands ###
