"""added refunded/removed delivered

Revision ID: ce97ed707cb4
Revises: 2b09fd02ea13
Create Date: 2021-04-29 10:38:57.477914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = 'ce97ed707cb4'
down_revision = '2b09fd02ea13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        text(
            """
    ALTER TABLE `order` MODIFY `order`.`status` ENUM(
        'failed', 
        'checking_out', 
        'paid', 
        'preparing',
        'out_for_delivery',
        'delivered',
        'complete',
        'refunded')
        """
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
