"""added date_arrived

Revision ID: d0f70eb55a79
Revises: a64a7a710fca
Create Date: 2021-06-13 15:36:16.984198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f70eb55a79'
down_revision = 'a64a7a710fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column(
        'date_arrived', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_arrived')
    # ### end Alembic commands ###
