"""added promo code

Revision ID: d2ca2778e609
Revises: a29acfdda9e3
Create Date: 2021-06-13 10:11:47.582259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ca2778e609'
down_revision = 'a29acfdda9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
