"""add promo_code_credit

Revision ID: e4d14c1982f1
Revises: 1ef9b08d23bd
Create Date: 2021-06-17 16:32:01.359193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d14c1982f1'
down_revision = '1ef9b08d23bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
