"""added address city, order dates, product tax

Revision ID: e50512287a16
Revises: a76ec9630978
Create Date: 2021-04-22 08:56:16.978413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50512287a16'
down_revision = 'a76ec9630978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date_complete', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('date_failed', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('date_out_for_delivery', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('date_prepared', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('tip_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'tip_amount')
    op.drop_column('order', 'date_prepared')
    op.drop_column('order', 'date_out_for_delivery')
    op.drop_column('order', 'date_failed')
    op.drop_column('order', 'date_complete')
    # ### end Alembic commands ###
