"""limit num redeems

Revision ID: e7e39ef38feb
Revises: c2a1e326854b
Create Date: 2021-08-04 16:48:11.584868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e39ef38feb'
down_revision = 'c2a1e326854b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('num_redeems_allowed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'num_redeems_allowed')
    # ### end Alembic commands ###
