"""migrate to cents

Revision ID: e910b4e661be
Revises: 2a9fe60fa318
Create Date: 2021-05-07 09:41:03.071538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e910b4e661be'
down_revision = '2a9fe60fa318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'cost', existing_type=sa.Float(),
                    type_=sa.Integer())
    op.alter_column('order', 'subtotal',
                    existing_type=sa.Float(), type_=sa.Integer())
    op.alter_column('order', 'delivery_charge',
                    existing_type=sa.Float(), type_=sa.Integer())
    op.alter_column('order', 'tip_amount',
                    existing_type=sa.Float(), type_=sa.Integer())
    op.alter_column('order', 'tax_charge',
                    existing_type=sa.Float(), type_=sa.Integer())
    op.alter_column('product', 'cost',
                    existing_type=sa.Float(), type_=sa.Integer())

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'cost',
                    existing_type=sa.Integer(), type_=sa.Float())
    op.alter_column('order', 'subtotal',
                    existing_type=sa.Integer(), type_=sa.Float())
    op.alter_column('order', 'delivery_charge',
                    existing_type=sa.Integer(), type_=sa.Float())
    op.alter_column('order', 'tax_charge',
                    existing_type=sa.Integer(), type_=sa.Float())
    op.alter_column('product', 'cost',
                    existing_type=sa.Integer(), type_=sa.Float())
    op.alter_column('order', 'tip_amount',
                    existing_type=sa.Integer(), type_=sa.Float())
    pass
    # ### end Alembic commands ###
